### PR TITLE
Change policy attach/detach API structure

### PR DESCRIPTION
**Pull request by taran-p**
Slightly restructures attach/detach for policies; sends information in PolicyAssociationReq struct instead of plain.

### CODE REVIEW

**Review by kannappanr — APPROVED** [review]

**Review by vadmeste — APPROVED** [review]
LGTM

**Review by vadmeste — CHANGES_REQUESTED** [review]
LGTM but this is a breaking change, we should briefly talk about this with @harshavardhana

**Review by harshavardhana — CHANGES_REQUESTED** [review]
@taran-p please add this as a new API instead of changing existing ones, we can remove this in future when we move to v3

**Comment by taran-p** [comment]
@harshavardhana Can do, but I was wondering if it would make sense to change these APIs since I added them recently and they aren't used for anything yet as far as I am aware

**Comment by harshavardhana** [comment]
> @harshavardhana Can do, but I was wondering if it would make sense to change these APIs since I added them recently and they aren't used for anything yet as far as I am aware

So if it's fairly new then it's not a problem.

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
